# Generated by Django 4.2.5 on 2023-10-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=100)),
                ('link', models.DateTimeField()),
                ('date', models.CharField(max_length=50)),
                ('Neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.neighborhood')),
            ],
        ),
    ]
