# Generated by Django 4.2.5 on 2023-10-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
