# Generated by Django 4.2.5 on 2023-10-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(max_length=50, null=True),
        ),
    ]
