# Generated by Django 4.2.5 on 2023-10-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_options_alter_news_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
