# Generated by Django 4.2.5 on 2023-10-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='neighborhood.house')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ispaid', models.BooleanField(default=False)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.paymentconcept')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.house')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('branch', models.CharField(max_length=30)),
                ('concept', models.CharField(max_length=50)),
                ('withdrawal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reference', models.CharField(max_length=30)),
                ('Neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.neighborhood')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.house')),
            ],
        ),
    ]
