# Generated by Django 4.2.5 on 2023-10-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconcept',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
