# Generated by Django 4.2.5 on 2023-10-08 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_alter_house_name_alter_house_phone_and_more'),
        ('savings', '0002_paymentconcept_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='branch',
        ),
        migrations.AlterField(
            model_name='balance',
            name='house',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='neighborhood.house'),
        ),
    ]
