# Generated by Django 4.2.5 on 2023-10-14 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_remove_movement_balance_remove_movement_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.balance'),
        ),
    ]
